### ISSUE TITLE
Sign Off Agreement

### ISSUE THREAD

**Issue by Lin87** [oel-mediateam/sbplus#42]
Check your name if you agree to release.

- [x] Ethan signed off
- [x] Bryan signed off
- [x] Patrick signed off
- [x] Moses signed off

**Comment by patrick-wirth** [comment]
Tested on Firefox 35.0.

**Comment by owlboy** [comment]
Tested on Firefox 34.05 Mac, and Chrome 39.0.2171.95 Mac.

**Comment by owlboy** [comment]
I also gave it a quick test in Firefox 35.0, looks good there too.
