### ISSUE TITLE
Test results from Moses

### ISSUE THREAD

**Issue by Lin87** [oel-mediateam/sbplus#44]
https://media.uwex.edu/sandbox/ethan/sbplus/index.html

**Please check-off each task once you completed or confirmed it.**

- [x] Clear browser cache
- [x] Check the SB+ script version is 2.5.9 (displayed at about 70% down the page): https://media.uwex.edu/sandbox/ethan/sbplus/sources/scripts/storybookplus.min.js
- [x] Video loads and plays in Firefox and using HTML5 player.
- [ ] OPTIONAL On Windows: Video loads and plays in Google Chrome, using HTML5 player, and texts are clear in all resolution
- [x] Spinning loading icon is not acting weird
- [x] Go to #42 and sign off

**Comment by mwolfensteinuwex** [comment]
Not sure what acting weird would be, but it seems to be working normally (running for just a second and then disappearing).

**Comment by Lin87** [comment]
Anything that is out of ordinary :wink:
