### ISSUE TITLE
MSMGT / SMGT Notes Logo

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus#46]
Hello,

I'm not sure if this should be working, or is working like intended, but MSMGT does not have an empty notes image. I think it should be the same as the SMGT one, since I have never heard of us having an MSMGT logo.

Example: https://media.uwex.edu/content/msmgt/msmgt710/msmgt710_lesson6/

**Comment by Lin87** [comment]
Not a bug... total forgot about MSMGT.

**Comment by owlboy** [comment]
Cool, simple fix!

**Comment by Lin87** [comment]
Fixed. Will be updating the script shortly.
