### ISSUE TITLE
Prevent Text Selection/Highlight in Chapter List

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus#47]
Sometimes I manage to select text in the chaper list when I intend to just click a chapter. Often a double click is what ends up highlighting the text.

Over the years this has been something I have been meaning to bring up. Here is some example css:

http://stackoverflow.com/questions/7059039/prevent-accidental-select-drag-highlight

We can't blanket apply this to the whole player since students might find reason to highlight text in the notes area.

**Comment by Lin87** [comment]
Okay. Easily done.

**Comment by Lin87** [comment]
Done. In update 2.6.0 coming (really) soon.

**Comment by owlboy** [comment]
Woo Hoo!
