### ISSUE TITLE
Testing results from Patrick

### ISSUE THREAD

**Issue by Lin87** [oel-mediateam/sbplus#49]
**Please check-off each task once you completed or confirmed it.**

- [ ] Clear browser cache.
- [ ] Check [jQuery script](https://media.uwex.edu/sandbox/ethan/sbplus/sources/scripts/jquery.min.js). Is the version number 2.1.3?
- [ ] Check [SB+ JS Script](https://media.uwex.edu/sandbox/ethan/sbplus/sources/scripts/storybookplus.min.js). Is the version number 2.6.0?
- [ ] Check [VideoJs script](https://media.uwex.edu/sandbox/ethan/sbplus/sources/videoplayer/combined.video.min.js) version. Is the version number 4.11.4?
- [ ] Go to [SB+ testing page](https://media.uwex.edu/sandbox/ethan/sbplus/build/).
- [ ] Download bar loads and supplement download button is shown?
- [ ] Click play. On the table of contents, does "Table of Contents" label shows up and stay fixed at the top?
- [ ] Try double clicking the table of contents list or the control buttons. The texts should not be able to be selected. The texts on the table of contents can be selected **if you attempt to select them like you would normally do**, but it will not persist.
- [ ] Click the "Expand" button. Click the "Table of Contents" button. Click the "Contract" button. Does the table of contents stay/show up at where it supposed to be?
- [ ] Click the "Expand" button again. Play with the "Table of Contents" toggle button and then click the "Contract" button. Does the table of contents still stay/show up at where it supposed to be?
- [ ] Navigate through each slide. All seems okay? Please pay special attentions to slide 2, 5, 6, 8, 10, 15, and 16.
- [ ] When navigate to an item on the table of content that is out of view, does the table of content auto scroll down? 
- [ ] Sign-off for release. Only check this box if you find no issues.

**Comment by patrick-wirth** [comment]
What's the URL I'm opening?

**Comment by Lin87** [comment]
It is linked on the tasks. The blue texts.

**Comment by patrick-wirth** [comment]
Looks good Ethan!
