### ISSUE TITLE
Testing results from Bryan

### ISSUE THREAD

**Issue by Lin87** [oel-mediateam/sbplus#51]
Before you start testing, please perform the following steps.

1. Launch Transmit app. If you have not setup Transmit, please follow the [Transmit documentation]( https://media.uwex.edu/resources/documentation/transmit/).
3. Navigate to your sandbox.
2. Delete the "build" folder in your sandbox. The "build" folder contains the GVP project files. This is not related to SB+, but it is good idea to remove files in your sandbox that we no longer use on the web server. We pay for storage space now.

If you have already done the steps above, thank you for taking your time to do it again.

**Please check-off each task once you completed or confirmed it.**

- [x] Clear browser cache.
- [x] Check [jQuery script](https://media.uwex.edu/sandbox/ethan/sbplus/sources/scripts/jquery.min.js). Is the version number 2.1.3?
- [x] Check [SB+ JS Script](https://media.uwex.edu/sandbox/ethan/sbplus/sources/scripts/storybookplus.min.js). Is the version number 2.6.0?
- [x] Check [VideoJs script](https://media.uwex.edu/sandbox/ethan/sbplus/sources/videoplayer/combined.video.min.js) version. Is the version number 4.11.4?
- [x] Go to [SB+ testing page](https://media.uwex.edu/sandbox/ethan/sbplus/build/).
- [x] Download bar loads and supplement download button is shown?
- [x] Click play. On the table of contents, does "Table of Contents" label shows up and stay fixed at the top?
- [x] Try double clicking the table of contents list or the control buttons. The texts should not be able to be selected. The texts on the table of contents can be selected **if you attempt to select them like you would normally do**, but it will not persist.
- [x] Click the "Expand" button. Click the "Table of Contents" button. Click the "Contract" button. Does the table of contents stay/show up at where it supposed to be?
- [x] Click the "Expand" button again. Play with the "Table of Contents" toggle button and then click the "Contract" button. Does the table of contents still stay/show up at where it supposed to be?
- [x] Navigate through each slide. All seems okay? Please pay special attentions to slide 2, 5, 6, 8, 10, 15, and 16.
- [x] When navigate to an item on the table of content that is out of view, does the table of content auto scroll down? 
- [ ] Sign-off for release. Only check this box if you find no issues.

**Comment by owlboy** [comment]
@Lin87 @mwolfensteinuwex @patrick-wirth I would like to propose we re-style the table of contents header. Right now it really sticks out, and I'm not sure I like the centered text. 

Here is what I would propose it look like:

![table-of-contents-re-style](https://cloud.githubusercontent.com/assets/237349/6923427/48a684d2-d797-11e4-874d-ff0d5ac2e988.png)

Any concerns with these changes?

**Comment by owlboy** [comment]
Also if note, I tested on Chrome 41.0.2272.104. It tells me I am up-to-date as of now.

**Comment by mwolfensteinuwex** [comment]
I don't have a super strong opinion about this, but I do see how it might be desirable to at least use a more uniform (lighter) color since the dark gray background seems to only be used for the audio player controls.I'm open to counter arguments on that if someone has a case to make. If so, we might want to do a quick test around the office.

I'm less concerned about centered vs left justified.

**Comment by owlboy** [comment]
Just an opinion, but Center Aligned text should be rarely used. And in this case it is the only thing other than the notes logo that is centered. That again helps to draw the eye to it and make it stand out among the rest of the player. And it's just the label for that area of the interface, it does not need to be so eye catching. :)

**Comment by mwolfensteinuwex** [comment]
I would counter that the reason we've inserted it is to draw attention to the fact that this is a table of contents that can be used for navigation, so on some level we do want it to be eye catching, just not distracting.

**Comment by owlboy** [comment]
@mwolfensteinuwex And for you, there are studies about the benefits and readability of left aligned text:

http://www.ixda.org/node/14744

**Comment by owlboy** [comment]
I would counter that the situation was that it was not obvious what it was. Now it has a label, easy to read and see if you are confused.

It needs to be clear, legible, and obvious what it is labeling. It does not have to be eye catching.

This is especially true since it is a simple concept that presumably does not need reminding and constant reinforcement.
