### ISSUE TITLE
Notes Section Blank with <note>yes</note> and No Notes on The Slide

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus#54]
For presentations that have some notes, but not on all slides, the ones without notes are not styled as such.

*Example (Slide 7 has notes):*
https://media.uwex.edu/content/msmgt/msmgt740/msmgt740_lesson13/index.html

The empty note area program logo should be shown in times when notes are not available for that slide.

**Comment by Lin87** [comment]
I'm aware of this issue when I was coding the logo script. I forgot the reason of why I did not do it then, but I will reinvestigate when time permits.

**Comment by owlboy** [comment]
Cool, that sounds good. It's best to make sure when there are no notes that it appears intentional, and not an error.

**Comment by Lin87** [comment]
Will be in version 2.7.0 feature release! :smiley:
