### ISSUE TITLE
Add Data Science logo to the Available Notes Section Logos

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus#55]
The data science logo needs to be added to the available logos in the notes section of the storybook player.

The directory name to detect is /ds/ just like /smgt/, /hwm/ etc.

If this could be pushed ahead of other Storybook+ updates, that would be great. Thanks!

You can ask Marla or Erin about getting the files if you are not sure where to find them on the Marketing Drive.

**Comment by Lin87** [comment]
Added in version 2.6.1

**Comment by owlboy** [comment]
Please make the following changes to the Data Science logo:

* The logo should be considered background or ambient branding, thus it should not command so much attention
    * Please make the logo smaller & lighter (see example)
* Please center the logo vertically based on the large "square that is in the icon. This ignores the arrow ascending above it. (see example)

![data_science_logo_changes](https://cloud.githubusercontent.com/assets/237349/9043383/a61e72dc-39da-11e5-9f98-173fc3fb8624.png)

**Comment by Lin87** [comment]
> Please make the logo smaller & lighter

The logo is the same size (250px &times; 108px) as with other logos. I made all logos smaller (150px &times; 65px), so they are consistent. DS logo is now lighter.

> Please center the logo vertically based on the large "square that is in the icon. This ignores the arrow ascending above it.

I am not making/coding special or custom padding just to accommodate the oddities of the current DS logo or future logos. All logo will center vertically or horizontally as long as they are within the ratio of 150px &times; 65px (30:13).

This update will be in version 2.7.0. For the moment and in effect, the logo stay the same size as other logo but lighter.

**Comment by owlboy** [comment]
> The logo is the same size (250px × 108px) as with other logos.

I respectfully disagree that they are the same size as the other logos.

![ds_logo-relative-size](https://cloud.githubusercontent.com/assets/237349/9049547/d9ff9a94-3a08-11e5-8623-e2c03d2a31c7.png)

Images used (from `app/storybook_plus_v2/img`): `ds_logo.svg`, `uw_bps_logo.svg`, `uw_ex_ceoel_logo.svg`, `uw_flx_logo.svg`, `uw_himt_logo.svg`, `uw_hwm_logo.svg`, `uw_il_logo.svg`, `uw_smgt_logo.svg`.

> I am not making/coding special or custom padding just to accommodate the oddities of the current DS logo or future logos.

I asked that the logo be smaller, not for a change in the positioning of the empty notes section logo.

I am only trying to balance the weight of the image relative to the content of the slides, and the the other logos.
As it stands now, the words "DATA SCIENCE" are larger than your average slide heading, and that should be the largest type on the slide (And thus the whole presentation) in most cases.

**Comment by Lin87** [comment]
If you think they are out of balance, please provide me with the "balanced" logos in SVG or PNG format. I will gladly update in the player.

I think they are fine and will not spend my time tweaking every single logos, so they are "balanced." I believe users know the differences (content-wise) between the texts in the logo and the texts on the slide.

Ethan Lin
ethan.lin@uwex.edu<mailto:ethan.lin@uwex.edu>

On Aug 3, 2015, at 5:56 PM, Bryan Bortz <notifications@github.com<mailto:notifications@github.com>> wrote:


The logo is the same size (250px ? 108px) as with other logos.

I respectfully disagree that they are the same size as the other logos.

[ds_logo-relative-size]<https://cloud.githubusercontent.com/assets/237349/9049547/d9ff9a94-3a08-11e5-8623-e2c03d2a31c7.png>

Images used (from app/storybook_plus_v2/img): ds_logo.svg, uw_bps_logo.svg, uw_ex_ceoel_logo.svg, uw_flx_logo.svg, uw_himt_logo.svg, uw_hwm_logo.svg, uw_il_logo.svg, uw_smgt_logo.svg.

I am not making/coding special or custom padding just to accommodate the oddities of the current DS logo or future logos.

I asked that the logo be smaller, not for a change in the positioning of the empty notes section logo.

I am only trying to balance the weight of the image relative to the content of the slides, and the the other logos.
As it stands now, the words "DATA SCIENCE" are larger than your average slide heading, and that should be the largest type on the slide (And thus the whole presentation) in most cases.

-
