### ISSUE TITLE
Erratic Scrolling

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus#56]
Chapter list scrolls to top when clicking entries in the top 40% of the visible table of contents view.

Watch this video to see what I mean:
https://www.youtube.com/watch?v=3EIOqd9eOow

**Comment by Lin87** [comment]
It is not being erratic. It just scrolling all the way up to the very begin when it is triggered. The fix and along with a few others will be in version 2.6.1 before version 2.7.0 (ADA stuff).

**Comment by Lin87** [comment]
Fixed in version 2.6.1.
