### ISSUE TITLE
Make the Color of Splash Screen Play Button Configurable

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus#58]
I realised, as we make more splash images of various designs and types, the bight blue Play Button on the splash screen may either clash, blend in too much, or otherwise not fit in nice with the splash image.

Would it be possible to add a variable to the `<setup>` tag called `<accent>`? It would hold a color hex code that can be used for the play button, and other parts of the player in the future if needed (hence the generic term "accent" instead of "playbuttoncolor" or something.

For example:
<setup>
`<accent>#FFC990</accent>`
</setup>
This would be a fantastic, and easy to work with, addition to the options contained in the topic.xml file.

**Comment by Lin87** [comment]
For now, it is just one play button that only shows up on the splash screen, which is not the main focused content. I can definitely change the color. But should we go to the extent of adding a value and coding to the player for something we might not even use in the future? What other parts of the player do you foresee in the future would benefit from this accent variable?

**Comment by Lin87** [comment]
Accent tag added in XML for version 2.7.0
