### ISSUE TITLE
Browser Zoom Under 100% Causes Display Issues in Firefox

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus#65]
Hello,

This is an issue Stephen just brought to my attention, and I am not sure how critical of a bug it is, or how easy it is to fix.

In Firefox, when you zoom below 100%, the table of contents gets wrapped down below the main content area/notes area.

![screen shot 2015-11-25 at 2 24 02 pm](https://cloud.githubusercontent.com/assets/237349/11408662/38b88318-9380-11e5-837c-8d27968af4f3.png)

**Comment by Lin87** [comment]
I had addressed this "issue" multiple times with the IDs. It drops down, because SB+ is not responsive. Current SB+ is exact pixel. Plus, it is *not* how responsive design works (by zooming).
Scaling up is fine because there is more pixels to play with. Scaling down, no extra pixels.

**Comment by owlboy** [comment]
I would argue that responsiveness does not come into play here. _Browser Zoom_ is different from _View Port_ resizing.

I would also note, scales fine in Webkit browsers. But if it's not an easy fix, or worth the effort. I understand.

**Comment by Lin87** [comment]
That's the thing, each *Browser Zoom* is different across browsers. Some may be smart (like webkit, which scale down the text and applies some responsive like design to it) or others (like Firefox) which only scale down text.

**Comment by owlboy** [comment]
When you say Firefox only scales down text, you don't mean Firefox __only__ scales down text right? 

Because all the divs and images and everything else are scaling. It seems the only thing that does not scale is the scrollbar.

**Comment by Lin87** [comment]
by text i mean everything. don't know how to describe the other things

**Comment by Lin87** [comment]
I can added one pixels to the wrapper which will not break if zoom out 3 or 4 times in firefox. Pass that it break again, which no longer our problem at that scale.

**Comment by owlboy** [comment]
Thank you!
